# Generated by Django 5.0.3 on 2024-04-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='growthrate',
        ),
    ]
