# Generated by Django 5.0.3 on 2024-04-03 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_consumptiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespAcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='frequency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequency',
            name='times_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthrate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthrate',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gender',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generation',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generation',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='growthrate',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.area')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.frequency')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gender')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.generation')),
                ('growthrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.growthrate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.respacq')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.style')),
            ],
        ),
    ]
