# Generated by Django 5.0.3 on 2024-04-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_productcat_product_product_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Style',
            new_name='FoodStyle',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='product',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='style',
            new_name='foodstyle',
        ),
        migrations.RenameModel(
            old_name='ProductCat',
            new_name='FoodCat',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('food_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.foodcat')),
            ],
        ),
        migrations.AddField(
            model_name='respondent',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.food'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
