# Generated by Django 5.0.3 on 2024-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_style_foodstyle_remove_respondent_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='cat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
