# Generated by Django 5.0.3 on 2024-04-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_frequency_cat_alter_frequency_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.area'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.frequency'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='growthrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.growthrate'),
        ),
    ]
