# Generated by Django 5.0.3 on 2024-04-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_respondent_area_alter_respondent_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='times_per_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthrate',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
