# Generated by Django 5.0.3 on 2024-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_food_image_foodstyle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
