# Generated by Django 5.0.3 on 2024-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_foodcat_image_alter_food_slug_alter_food_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcat',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
    ]
