# Generated by Django 5.0.3 on 2024-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_country_border_color_alter_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='short_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
