# Generated by Django 5.0.3 on 2024-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_food_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='border_color2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='border_color_empty',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='border_color_empty2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='color2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='color_empty',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='color_empty2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
