# Generated by Django 5.0.3 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_country_border_color2_country_border_color_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='border_color',
            field=models.CharField(default='rgba(0, 107, 162, 1)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='border_color2',
            field=models.CharField(default='rgba(62, 188, 210, 1)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='border_color_empty',
            field=models.CharField(default='rgba(152, 218, 255, 0)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='border_color_empty2',
            field=models.CharField(default='rgba(152, 218, 255, 0)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='color',
            field=models.CharField(default='rgba(0, 107, 162, 0.5)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='color2',
            field=models.CharField(default='rgba(62, 188, 210, 0.5)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='color_empty',
            field=models.CharField(default='rgba(152, 218, 255, 0.1)', max_length=25),
        ),
        migrations.AddField(
            model_name='food',
            name='color_empty2',
            field=models.CharField(default='rgba(152, 218, 255, 0.1)', max_length=25),
        ),
    ]
