# Generated by Django 5.0.3 on 2024-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_food_border_color_food_border_color2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthrate',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
