# Generated by Django 5.0.3 on 2024-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_frequency_order_growthrate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_background',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
