# Generated by Django 5.0.3 on 2024-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_food_image_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodstyle',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
