# Generated by Django 5.0.3 on 2024-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_area_order_foodstyle_order_generation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
