# Generated by Django 5.0.3 on 2024-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0023_country_order_gender_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="is_product",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="food",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
