# Generated by Django 5.0.3 on 2024-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0024_food_is_product_food_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodstyle",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
