# Generated by Django 5.0.3 on 2024-06-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_foodstyle_is_visible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_foods",
                    models.ManyToManyField(blank=True, to="dashboard.food"),
                ),
                (
                    "visible_foodstyles",
                    models.ManyToManyField(blank=True, to="dashboard.foodstyle"),
                ),
            ],
        ),
    ]
