# Generated by Django 5.0.3 on 2024-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0026_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="visible_foods",
            field=models.ManyToManyField(blank=True, null=True, to="dashboard.food"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="visible_foodstyles",
            field=models.ManyToManyField(
                blank=True, null=True, to="dashboard.foodstyle"
            ),
        ),
    ]
